'use client';

import * as React from 'react';
import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { useWizardState } from '@/lib/wizard/use-wizard-state';
import { GenerationRoadmap } from '@/components/wizard/GenerationRoadmap';
import { WizardSkeleton } from '@/components/wizard/WizardSkeleton';
import '@/styles/wizard.css';

const MOCK_REPORT = `# Growth Report

## Executive Summary
Based on the submitted brief, this analysis covers key performance indicators, audience trends, and actionable growth opportunities for the entity over the specified period.

## Key Findings
- **Revenue Growth**: +24% YoY driven by organic channel expansion
- **Audience Retention**: 68% 30-day retention, up from 54% prior period
- **Top Channel**: Direct search accounts for 41% of new user acquisition
- **Engagement Rate**: 3.2x industry average across core demographics

## Recommendations
1. Double down on top-performing content formats (short-form video +180% engagement)
2. Expand into adjacent audience segments — data shows 22% crossover potential
3. Optimize conversion funnel at checkout step 3 (current 34% drop-off rate)
4. Launch referral program: projected +15% new users at $4.20 CAC

## Data Sources
ActionNetwork · SocialBlade · Internal Analytics · Industry Benchmarks Q4 2024

---
*Report generated by Growth Report AI. For methodology details, see appendix.*`;

const STAGE_DELAYS_MS = [0, 800, 1600, 2400] as const;
const API_TIMEOUT_MS = 3000;

function getTemplateName(selectedTemplate: string | null): string {
  if (!selectedTemplate) return 'Default';
  // Humanize slug: "executive-summary" → "Executive Summary"
  return selectedTemplate
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function StepGenerate() {
  const { state, setStep, updateBrief } = useWizardState();
  const { brief, selectedTemplate } = state;

  const [generating, setGenerating] = useState(false);
  const [activeStage, setActiveStage] = useState<number>(-1);
  const [reportText, setReportText] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    setGenerating(true);
    setError(null);
    setReportText(null);
    setActiveStage(0);

    // Advance stage indicators on a fixed schedule
    const stageTimers: ReturnType<typeof setTimeout>[] = [];
    for (let i = 1; i < STAGE_DELAYS_MS.length; i++) {
      const stage = i;
      stageTimers.push(
        setTimeout(() => setActiveStage(stage), STAGE_DELAYS_MS[stage])
      );
    }

    // API call with mock fallback
    let result: string;
    const baseUrl = process.env.NEXT_PUBLIC_FRXNCOIS_API ?? '';

    if (baseUrl.length > 0) {
      try {
        const res = await fetch(`${baseUrl}/insights`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            entity: brief.entity,
            industry: brief.industry,
          }),
        });
        if (!res.ok) throw new Error(`API error ${res.status}`);
        const data = await res.json() as { report?: string; text?: string };
        result = data.report ?? data.text ?? MOCK_REPORT;
      } catch {
        // API failed — fall through to mock
        result = await mockFetch();
      }
    } else {
      result = await mockFetch();
    }

    // Clear pending stage timers
    stageTimers.forEach(clearTimeout);

    // Snap to final stage, then finish
    setActiveStage(3);
    await delay(500);

    setGenerating(false);
    setReportText(result);
    setActiveStage(-1);
  }, [brief.entity, brief.industry]);

  const handleTryAgain = useCallback(() => {
    setError(null);
    setReportText(null);
    setActiveStage(-1);
  }, []);

  const handleStartOver = useCallback(() => {
    setReportText(null);
    setError(null);
    setActiveStage(-1);
    setGenerating(false);
    updateBrief({ entity: '', industry: '', period: '' });
    setStep('brief');
  }, [setStep, updateBrief]);

  // --- Post-generation view ---
  if (reportText !== null) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] }}
        style={{ display: 'flex', flexDirection: 'column', gap: 24 }}
      >
        <div className="glass-panel" style={{ padding: 24 }}>
          <div
            style={{
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: '0.06em',
              textTransform: 'uppercase',
              color: 'rgba(255,255,255,0.35)',
              marginBottom: 16,
            }}
          >
            Generated Report
          </div>
          <pre
            style={{
              fontFamily: 'inherit',
              fontSize: 13,
              lineHeight: 1.7,
              color: 'rgba(255,255,255,0.8)',
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
              maxHeight: 400,
              overflowY: 'auto',
              margin: 0,
              padding: 0,
            }}
          >
            {reportText}
          </pre>
        </div>

        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <a
            href="#"
            aria-disabled="true"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '12px 24px',
              borderRadius: 999,
              background: 'linear-gradient(135deg, #7C3AED, #EC4899)',
              color: '#fff',
              fontSize: 14,
              fontWeight: 600,
              textDecoration: 'none',
              opacity: 0.6,
              cursor: 'not-allowed',
              pointerEvents: 'none',
            }}
            tabIndex={-1}
          >
            Download Report
          </a>

          <button
            onClick={handleStartOver}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '12px 24px',
              borderRadius: 999,
              border: '1px solid rgba(255,255,255,0.12)',
              background: 'transparent',
              color: 'rgba(255,255,255,0.7)',
              fontSize: 14,
              fontWeight: 600,
              cursor: 'pointer',
            }}
          >
            Start Over
          </button>
        </div>
      </motion.div>
    );
  }

  // --- Generating view ---
  if (generating) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
        <div className="glass-panel" style={{ padding: 28 }}>
          <div
            style={{
              fontSize: 13,
              fontWeight: 600,
              color: 'rgba(255,255,255,0.6)',
              marginBottom: 24,
              textAlign: 'center',
            }}
          >
            Building your report…
          </div>
          <GenerationRoadmap activeStage={activeStage} />
        </div>
        <WizardSkeleton />
      </div>
    );
  }

  // --- Error view ---
  if (error !== null) {
    return (
      <div className="glass-panel" style={{ padding: 28 }}>
        <div
          style={{
            fontSize: 14,
            color: '#F87171',
            marginBottom: 20,
            fontWeight: 500,
          }}
        >
          {error}
        </div>
        <button
          onClick={handleTryAgain}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            padding: '10px 22px',
            borderRadius: 999,
            border: 'none',
            background: 'linear-gradient(135deg, #7C3AED, #EC4899)',
            color: '#fff',
            fontSize: 14,
            fontWeight: 600,
            cursor: 'pointer',
          }}
        >
          Try Again
        </button>
      </div>
    );
  }

  // --- Idle / pre-generation view ---
  const templateName = getTemplateName(selectedTemplate);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Confirmation card */}
      <div className="glass-panel" style={{ padding: 28 }}>
        <div
          style={{
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
            color: 'rgba(255,255,255,0.35)',
            marginBottom: 20,
          }}
        >
          Report Summary
        </div>

        <dl
          style={{
            display: 'grid',
            gridTemplateColumns: 'max-content 1fr',
            gap: '10px 20px',
            margin: 0,
          }}
        >
          {[
            ['Entity', brief.entity || 'Not specified'],
            ['Industry', brief.industry || 'Not specified'],
            ['Period', brief.period || 'Not specified'],
            ['Template', templateName],
          ].map(([label, value]) => (
            <React.Fragment key={label}>
              <dt
                style={{
                  fontSize: 12,
                  color: 'rgba(255,255,255,0.35)',
                  fontWeight: 500,
                  margin: 0,
                }}
              >
                {label}
              </dt>
              <dd
                style={{
                  fontSize: 14,
                  color: 'rgba(255,255,255,0.85)',
                  fontWeight: 600,
                  margin: 0,
                }}
              >
                {value}
              </dd>
            </React.Fragment>
          ))}
        </dl>
      </div>

      {/* Action buttons */}
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
        <button
          onClick={() => setStep('template')}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            padding: '10px 20px',
            borderRadius: 999,
            border: '1px solid rgba(255,255,255,0.12)',
            background: 'transparent',
            color: 'rgba(255,255,255,0.6)',
            fontSize: 14,
            fontWeight: 500,
            cursor: 'pointer',
          }}
        >
          ← Back
        </button>

        <button
          onClick={handleGenerate}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 8,
            padding: '12px 32px',
            borderRadius: 999,
            border: 'none',
            background: 'linear-gradient(135deg, #7C3AED, #EC4899)',
            color: '#fff',
            fontSize: 15,
            fontWeight: 700,
            cursor: 'pointer',
            boxShadow: '0 4px 24px rgba(124,58,237,0.35)',
          }}
        >
          Generate Report
        </button>
      </div>
    </div>
  );
}

export default StepGenerate;

// --- Helpers ---

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function mockFetch(): Promise<string> {
  await delay(API_TIMEOUT_MS);
  return MOCK_REPORT;
}
